/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.housinggame.data.tables.records;


import nl.tudelft.simulation.housinggame.data.tables.SessionRole;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionRoleRecord extends UpdatableRecordImpl<SessionRoleRecord> implements Record4<Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gamedata.session_role.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gamedata.session_role.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gamedata.session_role.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>gamedata.session_role.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>gamedata.session_role.role_id</code>.
     */
    public void setRoleId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>gamedata.session_role.role_id</code>.
     */
    public Integer getRoleId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>gamedata.session_role.game_session_id</code>.
     */
    public void setGameSessionId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>gamedata.session_role.game_session_id</code>.
     */
    public Integer getGameSessionId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return SessionRole.SESSION_ROLE.ID;
    }

    @Override
    public Field<Integer> field2() {
        return SessionRole.SESSION_ROLE.USER_ID;
    }

    @Override
    public Field<Integer> field3() {
        return SessionRole.SESSION_ROLE.ROLE_ID;
    }

    @Override
    public Field<Integer> field4() {
        return SessionRole.SESSION_ROLE.GAME_SESSION_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getUserId();
    }

    @Override
    public Integer component3() {
        return getRoleId();
    }

    @Override
    public Integer component4() {
        return getGameSessionId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getUserId();
    }

    @Override
    public Integer value3() {
        return getRoleId();
    }

    @Override
    public Integer value4() {
        return getGameSessionId();
    }

    @Override
    public SessionRoleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SessionRoleRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public SessionRoleRecord value3(Integer value) {
        setRoleId(value);
        return this;
    }

    @Override
    public SessionRoleRecord value4(Integer value) {
        setGameSessionId(value);
        return this;
    }

    @Override
    public SessionRoleRecord values(Integer value1, Integer value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SessionRoleRecord
     */
    public SessionRoleRecord() {
        super(SessionRole.SESSION_ROLE);
    }

    /**
     * Create a detached, initialised SessionRoleRecord
     */
    public SessionRoleRecord(Integer id, Integer userId, Integer roleId, Integer gameSessionId) {
        super(SessionRole.SESSION_ROLE);

        setId(id);
        setUserId(userId);
        setRoleId(roleId);
        setGameSessionId(gameSessionId);
        resetChangedOnNotNull();
    }
}
