/*
 * This file is generated by jOOQ.
 */
package nl.gamedata.data.tables.records;


import nl.gamedata.data.tables.DashboardLayout;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DashboardLayoutRecord extends UpdatableRecordImpl<DashboardLayoutRecord> implements Record4<Integer, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gamedata.dashboard_layout.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gamedata.dashboard_layout.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gamedata.dashboard_layout.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gamedata.dashboard_layout.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gamedata.dashboard_layout.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gamedata.dashboard_layout.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gamedata.dashboard_layout.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gamedata.dashboard_layout.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DashboardLayout.DASHBOARD_LAYOUT.ID;
    }

    @Override
    public Field<String> field2() {
        return DashboardLayout.DASHBOARD_LAYOUT.CODE;
    }

    @Override
    public Field<String> field3() {
        return DashboardLayout.DASHBOARD_LAYOUT.NAME;
    }

    @Override
    public Field<String> field4() {
        return DashboardLayout.DASHBOARD_LAYOUT.DESCRIPTION;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCode();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCode();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public DashboardLayoutRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public DashboardLayoutRecord value2(String value) {
        setCode(value);
        return this;
    }

    @Override
    public DashboardLayoutRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public DashboardLayoutRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public DashboardLayoutRecord values(Integer value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DashboardLayoutRecord
     */
    public DashboardLayoutRecord() {
        super(DashboardLayout.DASHBOARD_LAYOUT);
    }

    /**
     * Create a detached, initialised DashboardLayoutRecord
     */
    public DashboardLayoutRecord(Integer id, String code, String name, String description) {
        super(DashboardLayout.DASHBOARD_LAYOUT);

        setId(id);
        setCode(code);
        setName(name);
        setDescription(description);
        resetChangedOnNotNull();
    }
}
