/*
 * This file is generated by jOOQ.
 */
package nl.gamedata.data.tables.records;


import nl.gamedata.data.tables.DashboardToken;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DashboardTokenRecord extends UpdatableRecordImpl<DashboardTokenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gamedata.dashboard_token.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gamedata.dashboard_token.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gamedata.dashboard_token.key</code>.
     */
    public void setKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gamedata.dashboard_token.key</code>.
     */
    public String getKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gamedata.dashboard_token.value</code>.
     */
    public void setValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gamedata.dashboard_token.value</code>.
     */
    public String getValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gamedata.dashboard_token.json</code>.
     */
    public void setJson(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>gamedata.dashboard_token.json</code>.
     */
    public Byte getJson() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>gamedata.dashboard_token.dashboard_id</code>.
     */
    public void setDashboardId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>gamedata.dashboard_token.dashboard_id</code>.
     */
    public Integer getDashboardId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DashboardTokenRecord
     */
    public DashboardTokenRecord() {
        super(DashboardToken.DASHBOARD_TOKEN);
    }

    /**
     * Create a detached, initialised DashboardTokenRecord
     */
    public DashboardTokenRecord(Integer id, String key, String value, Byte json, Integer dashboardId) {
        super(DashboardToken.DASHBOARD_TOKEN);

        setId(id);
        setKey(key);
        setValue(value);
        setJson(json);
        setDashboardId(dashboardId);
        resetChangedOnNotNull();
    }
}
