/*
 * This file is generated by jOOQ.
 */
package nl.gamedata.data.tables.records;


import nl.gamedata.data.tables.Dashboard;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DashboardRecord extends UpdatableRecordImpl<DashboardRecord> implements Record5<Integer, String, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gamedata.dashboard.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gamedata.dashboard.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gamedata.dashboard.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gamedata.dashboard.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gamedata.dashboard.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gamedata.dashboard.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gamedata.dashboard.query</code>.
     */
    public void setQuery(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gamedata.dashboard.query</code>.
     */
    public String getQuery() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gamedata.dashboard.dashboard_template_id</code>.
     */
    public void setDashboardTemplateId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>gamedata.dashboard.dashboard_template_id</code>.
     */
    public Integer getDashboardTemplateId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, String, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, String, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Dashboard.DASHBOARD.ID;
    }

    @Override
    public Field<String> field2() {
        return Dashboard.DASHBOARD.NAME;
    }

    @Override
    public Field<String> field3() {
        return Dashboard.DASHBOARD.DESCRIPTION;
    }

    @Override
    public Field<String> field4() {
        return Dashboard.DASHBOARD.QUERY;
    }

    @Override
    public Field<Integer> field5() {
        return Dashboard.DASHBOARD.DASHBOARD_TEMPLATE_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public String component4() {
        return getQuery();
    }

    @Override
    public Integer component5() {
        return getDashboardTemplateId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public String value4() {
        return getQuery();
    }

    @Override
    public Integer value5() {
        return getDashboardTemplateId();
    }

    @Override
    public DashboardRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public DashboardRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public DashboardRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public DashboardRecord value4(String value) {
        setQuery(value);
        return this;
    }

    @Override
    public DashboardRecord value5(Integer value) {
        setDashboardTemplateId(value);
        return this;
    }

    @Override
    public DashboardRecord values(Integer value1, String value2, String value3, String value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DashboardRecord
     */
    public DashboardRecord() {
        super(Dashboard.DASHBOARD);
    }

    /**
     * Create a detached, initialised DashboardRecord
     */
    public DashboardRecord(Integer id, String name, String description, String query, Integer dashboardTemplateId) {
        super(Dashboard.DASHBOARD);

        setId(id);
        setName(name);
        setDescription(description);
        setQuery(query);
        setDashboardTemplateId(dashboardTemplateId);
        resetChangedOnNotNull();
    }
}
