/*
 * This file is generated by jOOQ.
 */
package nl.gamedata.data.tables.records;


import nl.gamedata.data.tables.DashboardSetting;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DashboardSettingRecord extends UpdatableRecordImpl<DashboardSettingRecord> implements Record5<Integer, String, String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gamedata.dashboard_setting.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gamedata.dashboard_setting.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gamedata.dashboard_setting.key</code>.
     */
    public void setKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gamedata.dashboard_setting.key</code>.
     */
    public String getKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gamedata.dashboard_setting.value</code>.
     */
    public void setValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gamedata.dashboard_setting.value</code>.
     */
    public String getValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gamedata.dashboard_setting.organization_id</code>.
     */
    public void setOrganizationId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>gamedata.dashboard_setting.organization_id</code>.
     */
    public Integer getOrganizationId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>gamedata.dashboard_setting.game_mission_id</code>.
     */
    public void setGameMissionId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>gamedata.dashboard_setting.game_mission_id</code>.
     */
    public Integer getGameMissionId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DashboardSetting.DASHBOARD_SETTING.ID;
    }

    @Override
    public Field<String> field2() {
        return DashboardSetting.DASHBOARD_SETTING.KEY;
    }

    @Override
    public Field<String> field3() {
        return DashboardSetting.DASHBOARD_SETTING.VALUE;
    }

    @Override
    public Field<Integer> field4() {
        return DashboardSetting.DASHBOARD_SETTING.ORGANIZATION_ID;
    }

    @Override
    public Field<Integer> field5() {
        return DashboardSetting.DASHBOARD_SETTING.GAME_MISSION_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getKey();
    }

    @Override
    public String component3() {
        return getValue();
    }

    @Override
    public Integer component4() {
        return getOrganizationId();
    }

    @Override
    public Integer component5() {
        return getGameMissionId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getKey();
    }

    @Override
    public String value3() {
        return getValue();
    }

    @Override
    public Integer value4() {
        return getOrganizationId();
    }

    @Override
    public Integer value5() {
        return getGameMissionId();
    }

    @Override
    public DashboardSettingRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public DashboardSettingRecord value2(String value) {
        setKey(value);
        return this;
    }

    @Override
    public DashboardSettingRecord value3(String value) {
        setValue(value);
        return this;
    }

    @Override
    public DashboardSettingRecord value4(Integer value) {
        setOrganizationId(value);
        return this;
    }

    @Override
    public DashboardSettingRecord value5(Integer value) {
        setGameMissionId(value);
        return this;
    }

    @Override
    public DashboardSettingRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DashboardSettingRecord
     */
    public DashboardSettingRecord() {
        super(DashboardSetting.DASHBOARD_SETTING);
    }

    /**
     * Create a detached, initialised DashboardSettingRecord
     */
    public DashboardSettingRecord(Integer id, String key, String value, Integer organizationId, Integer gameMissionId) {
        super(DashboardSetting.DASHBOARD_SETTING);

        setId(id);
        setKey(key);
        setValue(value);
        setOrganizationId(organizationId);
        setGameMissionId(gameMissionId);
        resetChangedOnNotNull();
    }
}
