/*
 * This file is generated by jOOQ.
 */
package nl.gamedata.data.tables.records;


import nl.gamedata.data.tables.DashboardLayout;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DashboardLayoutRecord extends UpdatableRecordImpl<DashboardLayoutRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gamedata.dashboard_layout.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gamedata.dashboard_layout.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gamedata.dashboard_layout.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gamedata.dashboard_layout.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gamedata.dashboard_layout.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gamedata.dashboard_layout.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gamedata.dashboard_layout.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gamedata.dashboard_layout.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DashboardLayoutRecord
     */
    public DashboardLayoutRecord() {
        super(DashboardLayout.DASHBOARD_LAYOUT);
    }

    /**
     * Create a detached, initialised DashboardLayoutRecord
     */
    public DashboardLayoutRecord(Integer id, String code, String name, String description) {
        super(DashboardLayout.DASHBOARD_LAYOUT);

        setId(id);
        setCode(code);
        setName(name);
        setDescription(description);
        resetChangedOnNotNull();
    }
}
