/*
 * This file is generated by jOOQ.
 */
package nl.gamedata.data.tables.records;


import nl.gamedata.data.tables.DashboardTemplate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DashboardTemplateRecord extends UpdatableRecordImpl<DashboardTemplateRecord> implements Record9<Integer, String, String, String, Byte, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gamedata.dashboard_template.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gamedata.dashboard_template.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gamedata.dashboard_template.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gamedata.dashboard_template.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gamedata.dashboard_template.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gamedata.dashboard_template.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gamedata.dashboard_template.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gamedata.dashboard_template.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gamedata.dashboard_template.private</code>.
     */
    public void setPrivate(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>gamedata.dashboard_template.private</code>.
     */
    public Byte getPrivate() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>gamedata.dashboard_template.game_version_id</code>.
     */
    public void setGameVersionId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>gamedata.dashboard_template.game_version_id</code>.
     */
    public Integer getGameVersionId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>gamedata.dashboard_template.game_mission_id</code>.
     */
    public void setGameMissionId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>gamedata.dashboard_template.game_mission_id</code>.
     */
    public Integer getGameMissionId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>gamedata.dashboard_template.organization_game_id</code>.
     */
    public void setOrganizationGameId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>gamedata.dashboard_template.organization_game_id</code>.
     */
    public Integer getOrganizationGameId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>gamedata.dashboard_template.dashboard_layout_id</code>.
     */
    public void setDashboardLayoutId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>gamedata.dashboard_template.dashboard_layout_id</code>.
     */
    public Integer getDashboardLayoutId() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, String, String, String, Byte, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, String, String, String, Byte, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DashboardTemplate.DASHBOARD_TEMPLATE.ID;
    }

    @Override
    public Field<String> field2() {
        return DashboardTemplate.DASHBOARD_TEMPLATE.CODE;
    }

    @Override
    public Field<String> field3() {
        return DashboardTemplate.DASHBOARD_TEMPLATE.NAME;
    }

    @Override
    public Field<String> field4() {
        return DashboardTemplate.DASHBOARD_TEMPLATE.DESCRIPTION;
    }

    @Override
    public Field<Byte> field5() {
        return DashboardTemplate.DASHBOARD_TEMPLATE.PRIVATE;
    }

    @Override
    public Field<Integer> field6() {
        return DashboardTemplate.DASHBOARD_TEMPLATE.GAME_VERSION_ID;
    }

    @Override
    public Field<Integer> field7() {
        return DashboardTemplate.DASHBOARD_TEMPLATE.GAME_MISSION_ID;
    }

    @Override
    public Field<Integer> field8() {
        return DashboardTemplate.DASHBOARD_TEMPLATE.ORGANIZATION_GAME_ID;
    }

    @Override
    public Field<Integer> field9() {
        return DashboardTemplate.DASHBOARD_TEMPLATE.DASHBOARD_LAYOUT_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCode();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public Byte component5() {
        return getPrivate();
    }

    @Override
    public Integer component6() {
        return getGameVersionId();
    }

    @Override
    public Integer component7() {
        return getGameMissionId();
    }

    @Override
    public Integer component8() {
        return getOrganizationGameId();
    }

    @Override
    public Integer component9() {
        return getDashboardLayoutId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCode();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public Byte value5() {
        return getPrivate();
    }

    @Override
    public Integer value6() {
        return getGameVersionId();
    }

    @Override
    public Integer value7() {
        return getGameMissionId();
    }

    @Override
    public Integer value8() {
        return getOrganizationGameId();
    }

    @Override
    public Integer value9() {
        return getDashboardLayoutId();
    }

    @Override
    public DashboardTemplateRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public DashboardTemplateRecord value2(String value) {
        setCode(value);
        return this;
    }

    @Override
    public DashboardTemplateRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public DashboardTemplateRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public DashboardTemplateRecord value5(Byte value) {
        setPrivate(value);
        return this;
    }

    @Override
    public DashboardTemplateRecord value6(Integer value) {
        setGameVersionId(value);
        return this;
    }

    @Override
    public DashboardTemplateRecord value7(Integer value) {
        setGameMissionId(value);
        return this;
    }

    @Override
    public DashboardTemplateRecord value8(Integer value) {
        setOrganizationGameId(value);
        return this;
    }

    @Override
    public DashboardTemplateRecord value9(Integer value) {
        setDashboardLayoutId(value);
        return this;
    }

    @Override
    public DashboardTemplateRecord values(Integer value1, String value2, String value3, String value4, Byte value5, Integer value6, Integer value7, Integer value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DashboardTemplateRecord
     */
    public DashboardTemplateRecord() {
        super(DashboardTemplate.DASHBOARD_TEMPLATE);
    }

    /**
     * Create a detached, initialised DashboardTemplateRecord
     */
    public DashboardTemplateRecord(Integer id, String code, String name, String description, Byte private_, Integer gameVersionId, Integer gameMissionId, Integer organizationGameId, Integer dashboardLayoutId) {
        super(DashboardTemplate.DASHBOARD_TEMPLATE);

        setId(id);
        setCode(code);
        setName(name);
        setDescription(description);
        setPrivate(private_);
        setGameVersionId(gameVersionId);
        setGameMissionId(gameMissionId);
        setOrganizationGameId(organizationGameId);
        setDashboardLayoutId(dashboardLayoutId);
        resetChangedOnNotNull();
    }
}
