/*
 * This file is generated by jOOQ.
 */
package nl.gamedata.data.tables.records;


import nl.gamedata.data.tables.GameVersion;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameVersionRecord extends UpdatableRecordImpl<GameVersionRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gamedata.game_version.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gamedata.game_version.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gamedata.game_version.version</code>.
     */
    public void setVersion(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gamedata.game_version.version</code>.
     */
    public String getVersion() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gamedata.game_version.game_id</code>.
     */
    public void setGameId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>gamedata.game_version.game_id</code>.
     */
    public Integer getGameId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return GameVersion.GAME_VERSION.ID;
    }

    @Override
    public Field<String> field2() {
        return GameVersion.GAME_VERSION.VERSION;
    }

    @Override
    public Field<Integer> field3() {
        return GameVersion.GAME_VERSION.GAME_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getVersion();
    }

    @Override
    public Integer component3() {
        return getGameId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getVersion();
    }

    @Override
    public Integer value3() {
        return getGameId();
    }

    @Override
    public GameVersionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public GameVersionRecord value2(String value) {
        setVersion(value);
        return this;
    }

    @Override
    public GameVersionRecord value3(Integer value) {
        setGameId(value);
        return this;
    }

    @Override
    public GameVersionRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameVersionRecord
     */
    public GameVersionRecord() {
        super(GameVersion.GAME_VERSION);
    }

    /**
     * Create a detached, initialised GameVersionRecord
     */
    public GameVersionRecord(Integer id, String version, Integer gameId) {
        super(GameVersion.GAME_VERSION);

        setId(id);
        setVersion(version);
        setGameId(gameId);
        resetChangedOnNotNull();
    }
}
