/*
 * This file is generated by jOOQ.
 */
package nl.gamedata.data.tables.records;


import nl.gamedata.data.tables.GameToken;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameTokenRecord extends UpdatableRecordImpl<GameTokenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gamedata.game_token.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gamedata.game_token.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gamedata.game_token.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gamedata.game_token.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gamedata.game_token.value</code>.
     */
    public void setValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gamedata.game_token.value</code>.
     */
    public String getValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gamedata.game_token.writer</code>.
     */
    public void setWriter(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>gamedata.game_token.writer</code>.
     */
    public Byte getWriter() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>gamedata.game_token.reader</code>.
     */
    public void setReader(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>gamedata.game_token.reader</code>.
     */
    public Byte getReader() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>gamedata.game_token.game_id</code>.
     */
    public void setGameId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>gamedata.game_token.game_id</code>.
     */
    public Integer getGameId() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameTokenRecord
     */
    public GameTokenRecord() {
        super(GameToken.GAME_TOKEN);
    }

    /**
     * Create a detached, initialised GameTokenRecord
     */
    public GameTokenRecord(Integer id, String name, String value, Byte writer, Byte reader, Integer gameId) {
        super(GameToken.GAME_TOKEN);

        setId(id);
        setName(name);
        setValue(value);
        setWriter(writer);
        setReader(reader);
        setGameId(gameId);
        resetChangedOnNotNull();
    }
}
