/*
 * This file is generated by jOOQ.
 */
package nl.gamedata.data.tables.records;


import nl.gamedata.data.tables.Game;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameRecord extends UpdatableRecordImpl<GameRecord> implements Record7<Integer, String, String, String, Byte, Byte, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gamedata.game.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gamedata.game.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gamedata.game.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gamedata.game.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gamedata.game.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gamedata.game.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gamedata.game.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gamedata.game.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gamedata.game.token_forced</code>.
     */
    public void setTokenForced(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>gamedata.game.token_forced</code>.
     */
    public Byte getTokenForced() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>gamedata.game.archived</code>.
     */
    public void setArchived(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>gamedata.game.archived</code>.
     */
    public Byte getArchived() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>gamedata.game.logo</code>.
     */
    public void setLogo(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>gamedata.game.logo</code>.
     */
    public String getLogo() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, Byte, Byte, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, String, Byte, Byte, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Game.GAME.ID;
    }

    @Override
    public Field<String> field2() {
        return Game.GAME.CODE;
    }

    @Override
    public Field<String> field3() {
        return Game.GAME.NAME;
    }

    @Override
    public Field<String> field4() {
        return Game.GAME.DESCRIPTION;
    }

    @Override
    public Field<Byte> field5() {
        return Game.GAME.TOKEN_FORCED;
    }

    @Override
    public Field<Byte> field6() {
        return Game.GAME.ARCHIVED;
    }

    @Override
    public Field<String> field7() {
        return Game.GAME.LOGO;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCode();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public Byte component5() {
        return getTokenForced();
    }

    @Override
    public Byte component6() {
        return getArchived();
    }

    @Override
    public String component7() {
        return getLogo();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCode();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public Byte value5() {
        return getTokenForced();
    }

    @Override
    public Byte value6() {
        return getArchived();
    }

    @Override
    public String value7() {
        return getLogo();
    }

    @Override
    public GameRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public GameRecord value2(String value) {
        setCode(value);
        return this;
    }

    @Override
    public GameRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public GameRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public GameRecord value5(Byte value) {
        setTokenForced(value);
        return this;
    }

    @Override
    public GameRecord value6(Byte value) {
        setArchived(value);
        return this;
    }

    @Override
    public GameRecord value7(String value) {
        setLogo(value);
        return this;
    }

    @Override
    public GameRecord values(Integer value1, String value2, String value3, String value4, Byte value5, Byte value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameRecord
     */
    public GameRecord() {
        super(Game.GAME);
    }

    /**
     * Create a detached, initialised GameRecord
     */
    public GameRecord(Integer id, String code, String name, String description, Byte tokenForced, Byte archived, String logo) {
        super(Game.GAME);

        setId(id);
        setCode(code);
        setName(name);
        setDescription(description);
        setTokenForced(tokenForced);
        setArchived(archived);
        setLogo(logo);
        resetChangedOnNotNull();
    }
}
