/*
 * This file is generated by jOOQ.
 */
package nl.gamedata.data.tables.records;


import nl.gamedata.data.tables.GameSessionRole;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameSessionRoleRecord extends UpdatableRecordImpl<GameSessionRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gamedata.game_session_role.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gamedata.game_session_role.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gamedata.game_session_role.view</code>.
     */
    public void setView(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>gamedata.game_session_role.view</code>.
     */
    public Byte getView() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>gamedata.game_session_role.edit</code>.
     */
    public void setEdit(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>gamedata.game_session_role.edit</code>.
     */
    public Byte getEdit() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>gamedata.game_session_role.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>gamedata.game_session_role.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>gamedata.game_session_role.game_session_id</code>.
     */
    public void setGameSessionId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>gamedata.game_session_role.game_session_id</code>.
     */
    public Integer getGameSessionId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameSessionRoleRecord
     */
    public GameSessionRoleRecord() {
        super(GameSessionRole.GAME_SESSION_ROLE);
    }

    /**
     * Create a detached, initialised GameSessionRoleRecord
     */
    public GameSessionRoleRecord(Integer id, Byte view, Byte edit, Integer userId, Integer gameSessionId) {
        super(GameSessionRole.GAME_SESSION_ROLE);

        setId(id);
        setView(view);
        setEdit(edit);
        setUserId(userId);
        setGameSessionId(gameSessionId);
        resetChangedOnNotNull();
    }
}
