/*
 * This file is generated by jOOQ.
 */
package nl.gamedata.data.tables.records;


import nl.gamedata.data.tables.OrganizationGameRole;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrganizationGameRoleRecord extends UpdatableRecordImpl<OrganizationGameRoleRecord> implements Record5<Integer, Byte, Byte, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gamedata.organization_game_role.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gamedata.organization_game_role.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gamedata.organization_game_role.view</code>.
     */
    public void setView(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>gamedata.organization_game_role.view</code>.
     */
    public Byte getView() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>gamedata.organization_game_role.edit</code>.
     */
    public void setEdit(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>gamedata.organization_game_role.edit</code>.
     */
    public Byte getEdit() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>gamedata.organization_game_role.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>gamedata.organization_game_role.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(3);
    }

    /**
     * Setter for
     * <code>gamedata.organization_game_role.organization_game_id</code>.
     */
    public void setOrganizationGameId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>gamedata.organization_game_role.organization_game_id</code>.
     */
    public Integer getOrganizationGameId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Byte, Byte, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Byte, Byte, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return OrganizationGameRole.ORGANIZATION_GAME_ROLE.ID;
    }

    @Override
    public Field<Byte> field2() {
        return OrganizationGameRole.ORGANIZATION_GAME_ROLE.VIEW;
    }

    @Override
    public Field<Byte> field3() {
        return OrganizationGameRole.ORGANIZATION_GAME_ROLE.EDIT;
    }

    @Override
    public Field<Integer> field4() {
        return OrganizationGameRole.ORGANIZATION_GAME_ROLE.USER_ID;
    }

    @Override
    public Field<Integer> field5() {
        return OrganizationGameRole.ORGANIZATION_GAME_ROLE.ORGANIZATION_GAME_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Byte component2() {
        return getView();
    }

    @Override
    public Byte component3() {
        return getEdit();
    }

    @Override
    public Integer component4() {
        return getUserId();
    }

    @Override
    public Integer component5() {
        return getOrganizationGameId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Byte value2() {
        return getView();
    }

    @Override
    public Byte value3() {
        return getEdit();
    }

    @Override
    public Integer value4() {
        return getUserId();
    }

    @Override
    public Integer value5() {
        return getOrganizationGameId();
    }

    @Override
    public OrganizationGameRoleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public OrganizationGameRoleRecord value2(Byte value) {
        setView(value);
        return this;
    }

    @Override
    public OrganizationGameRoleRecord value3(Byte value) {
        setEdit(value);
        return this;
    }

    @Override
    public OrganizationGameRoleRecord value4(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public OrganizationGameRoleRecord value5(Integer value) {
        setOrganizationGameId(value);
        return this;
    }

    @Override
    public OrganizationGameRoleRecord values(Integer value1, Byte value2, Byte value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrganizationGameRoleRecord
     */
    public OrganizationGameRoleRecord() {
        super(OrganizationGameRole.ORGANIZATION_GAME_ROLE);
    }

    /**
     * Create a detached, initialised OrganizationGameRoleRecord
     */
    public OrganizationGameRoleRecord(Integer id, Byte view, Byte edit, Integer userId, Integer organizationGameId) {
        super(OrganizationGameRole.ORGANIZATION_GAME_ROLE);

        setId(id);
        setView(view);
        setEdit(edit);
        setUserId(userId);
        setOrganizationGameId(organizationGameId);
        resetChangedOnNotNull();
    }
}
