/*
 * This file is generated by jOOQ.
 */
package nl.gamedata.data.tables.records;


import java.time.LocalDateTime;

import nl.gamedata.data.tables.PlayerAction;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerActionRecord extends UpdatableRecordImpl<PlayerActionRecord> implements Record11<Integer, String, String, String, LocalDateTime, Integer, String, String, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gamedata.player_action.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gamedata.player_action.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gamedata.player_action.type</code>.
     */
    public void setType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gamedata.player_action.type</code>.
     */
    public String getType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gamedata.player_action.key</code>.
     */
    public void setKey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gamedata.player_action.key</code>.
     */
    public String getKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gamedata.player_action.value</code>.
     */
    public void setValue(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gamedata.player_action.value</code>.
     */
    public String getValue() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gamedata.player_action.timestamp</code>.
     */
    public void setTimestamp(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>gamedata.player_action.timestamp</code>.
     */
    public LocalDateTime getTimestamp() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>gamedata.player_action.mission_attempt</code>.
     */
    public void setMissionAttempt(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>gamedata.player_action.mission_attempt</code>.
     */
    public Integer getMissionAttempt() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>gamedata.player_action.status</code>.
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>gamedata.player_action.status</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>gamedata.player_action.round</code>.
     */
    public void setRound(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>gamedata.player_action.round</code>.
     */
    public String getRound() {
        return (String) get(7);
    }

    /**
     * Setter for <code>gamedata.player_action.game_time</code>.
     */
    public void setGameTime(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>gamedata.player_action.game_time</code>.
     */
    public String getGameTime() {
        return (String) get(8);
    }

    /**
     * Setter for <code>gamedata.player_action.grouping_code</code>.
     */
    public void setGroupingCode(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>gamedata.player_action.grouping_code</code>.
     */
    public String getGroupingCode() {
        return (String) get(9);
    }

    /**
     * Setter for <code>gamedata.player_action.player_attempt_id</code>.
     */
    public void setPlayerAttemptId(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>gamedata.player_action.player_attempt_id</code>.
     */
    public Integer getPlayerAttemptId() {
        return (Integer) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Integer, String, String, String, LocalDateTime, Integer, String, String, String, String, Integer> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Integer, String, String, String, LocalDateTime, Integer, String, String, String, String, Integer> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PlayerAction.PLAYER_ACTION.ID;
    }

    @Override
    public Field<String> field2() {
        return PlayerAction.PLAYER_ACTION.TYPE;
    }

    @Override
    public Field<String> field3() {
        return PlayerAction.PLAYER_ACTION.KEY;
    }

    @Override
    public Field<String> field4() {
        return PlayerAction.PLAYER_ACTION.VALUE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return PlayerAction.PLAYER_ACTION.TIMESTAMP;
    }

    @Override
    public Field<Integer> field6() {
        return PlayerAction.PLAYER_ACTION.MISSION_ATTEMPT;
    }

    @Override
    public Field<String> field7() {
        return PlayerAction.PLAYER_ACTION.STATUS;
    }

    @Override
    public Field<String> field8() {
        return PlayerAction.PLAYER_ACTION.ROUND;
    }

    @Override
    public Field<String> field9() {
        return PlayerAction.PLAYER_ACTION.GAME_TIME;
    }

    @Override
    public Field<String> field10() {
        return PlayerAction.PLAYER_ACTION.GROUPING_CODE;
    }

    @Override
    public Field<Integer> field11() {
        return PlayerAction.PLAYER_ACTION.PLAYER_ATTEMPT_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getType();
    }

    @Override
    public String component3() {
        return getKey();
    }

    @Override
    public String component4() {
        return getValue();
    }

    @Override
    public LocalDateTime component5() {
        return getTimestamp();
    }

    @Override
    public Integer component6() {
        return getMissionAttempt();
    }

    @Override
    public String component7() {
        return getStatus();
    }

    @Override
    public String component8() {
        return getRound();
    }

    @Override
    public String component9() {
        return getGameTime();
    }

    @Override
    public String component10() {
        return getGroupingCode();
    }

    @Override
    public Integer component11() {
        return getPlayerAttemptId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getType();
    }

    @Override
    public String value3() {
        return getKey();
    }

    @Override
    public String value4() {
        return getValue();
    }

    @Override
    public LocalDateTime value5() {
        return getTimestamp();
    }

    @Override
    public Integer value6() {
        return getMissionAttempt();
    }

    @Override
    public String value7() {
        return getStatus();
    }

    @Override
    public String value8() {
        return getRound();
    }

    @Override
    public String value9() {
        return getGameTime();
    }

    @Override
    public String value10() {
        return getGroupingCode();
    }

    @Override
    public Integer value11() {
        return getPlayerAttemptId();
    }

    @Override
    public PlayerActionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PlayerActionRecord value2(String value) {
        setType(value);
        return this;
    }

    @Override
    public PlayerActionRecord value3(String value) {
        setKey(value);
        return this;
    }

    @Override
    public PlayerActionRecord value4(String value) {
        setValue(value);
        return this;
    }

    @Override
    public PlayerActionRecord value5(LocalDateTime value) {
        setTimestamp(value);
        return this;
    }

    @Override
    public PlayerActionRecord value6(Integer value) {
        setMissionAttempt(value);
        return this;
    }

    @Override
    public PlayerActionRecord value7(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public PlayerActionRecord value8(String value) {
        setRound(value);
        return this;
    }

    @Override
    public PlayerActionRecord value9(String value) {
        setGameTime(value);
        return this;
    }

    @Override
    public PlayerActionRecord value10(String value) {
        setGroupingCode(value);
        return this;
    }

    @Override
    public PlayerActionRecord value11(Integer value) {
        setPlayerAttemptId(value);
        return this;
    }

    @Override
    public PlayerActionRecord values(Integer value1, String value2, String value3, String value4, LocalDateTime value5, Integer value6, String value7, String value8, String value9, String value10, Integer value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlayerActionRecord
     */
    public PlayerActionRecord() {
        super(PlayerAction.PLAYER_ACTION);
    }

    /**
     * Create a detached, initialised PlayerActionRecord
     */
    public PlayerActionRecord(Integer id, String type, String key, String value, LocalDateTime timestamp, Integer missionAttempt, String status, String round, String gameTime, String groupingCode, Integer playerAttemptId) {
        super(PlayerAction.PLAYER_ACTION);

        setId(id);
        setType(type);
        setKey(key);
        setValue(value);
        setTimestamp(timestamp);
        setMissionAttempt(missionAttempt);
        setStatus(status);
        setRound(round);
        setGameTime(gameTime);
        setGroupingCode(groupingCode);
        setPlayerAttemptId(playerAttemptId);
        resetChangedOnNotNull();
    }
}
