/*
 * This file is generated by jOOQ.
 */
package nl.gamedata.data.tables.records;


import nl.gamedata.data.tables.Player;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerRecord extends UpdatableRecordImpl<PlayerRecord> implements Record4<Integer, String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gamedata.player.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gamedata.player.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gamedata.player.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gamedata.player.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gamedata.player.game_session_id</code>.
     */
    public void setGameSessionId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>gamedata.player.game_session_id</code>.
     */
    public Integer getGameSessionId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>gamedata.player.group_role_id</code>.
     */
    public void setGroupRoleId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>gamedata.player.group_role_id</code>.
     */
    public Integer getGroupRoleId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Player.PLAYER.ID;
    }

    @Override
    public Field<String> field2() {
        return Player.PLAYER.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return Player.PLAYER.GAME_SESSION_ID;
    }

    @Override
    public Field<Integer> field4() {
        return Player.PLAYER.GROUP_ROLE_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getGameSessionId();
    }

    @Override
    public Integer component4() {
        return getGroupRoleId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getGameSessionId();
    }

    @Override
    public Integer value4() {
        return getGroupRoleId();
    }

    @Override
    public PlayerRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PlayerRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public PlayerRecord value3(Integer value) {
        setGameSessionId(value);
        return this;
    }

    @Override
    public PlayerRecord value4(Integer value) {
        setGroupRoleId(value);
        return this;
    }

    @Override
    public PlayerRecord values(Integer value1, String value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlayerRecord
     */
    public PlayerRecord() {
        super(Player.PLAYER);
    }

    /**
     * Create a detached, initialised PlayerRecord
     */
    public PlayerRecord(Integer id, String name, Integer gameSessionId, Integer groupRoleId) {
        super(Player.PLAYER);

        setId(id);
        setName(name);
        setGameSessionId(gameSessionId);
        setGroupRoleId(groupRoleId);
        resetChangedOnNotNull();
    }
}
