/*
 * This file is generated by jOOQ.
 */
package nl.gamedata.data.tables.records;


import nl.gamedata.data.tables.PlayerObjective;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerObjectiveRecord extends UpdatableRecordImpl<PlayerObjectiveRecord> implements Record5<Integer, String, String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gamedata.player_objective.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gamedata.player_objective.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gamedata.player_objective.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gamedata.player_objective.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gamedata.player_objective.threshold</code>.
     */
    public void setThreshold(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gamedata.player_objective.threshold</code>.
     */
    public String getThreshold() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gamedata.player_objective.game_mission_id</code>.
     */
    public void setGameMissionId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>gamedata.player_objective.game_mission_id</code>.
     */
    public Integer getGameMissionId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>gamedata.player_objective.scale_id</code>.
     */
    public void setScaleId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>gamedata.player_objective.scale_id</code>.
     */
    public Integer getScaleId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PlayerObjective.PLAYER_OBJECTIVE.ID;
    }

    @Override
    public Field<String> field2() {
        return PlayerObjective.PLAYER_OBJECTIVE.NAME;
    }

    @Override
    public Field<String> field3() {
        return PlayerObjective.PLAYER_OBJECTIVE.THRESHOLD;
    }

    @Override
    public Field<Integer> field4() {
        return PlayerObjective.PLAYER_OBJECTIVE.GAME_MISSION_ID;
    }

    @Override
    public Field<Integer> field5() {
        return PlayerObjective.PLAYER_OBJECTIVE.SCALE_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getThreshold();
    }

    @Override
    public Integer component4() {
        return getGameMissionId();
    }

    @Override
    public Integer component5() {
        return getScaleId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getThreshold();
    }

    @Override
    public Integer value4() {
        return getGameMissionId();
    }

    @Override
    public Integer value5() {
        return getScaleId();
    }

    @Override
    public PlayerObjectiveRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PlayerObjectiveRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public PlayerObjectiveRecord value3(String value) {
        setThreshold(value);
        return this;
    }

    @Override
    public PlayerObjectiveRecord value4(Integer value) {
        setGameMissionId(value);
        return this;
    }

    @Override
    public PlayerObjectiveRecord value5(Integer value) {
        setScaleId(value);
        return this;
    }

    @Override
    public PlayerObjectiveRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlayerObjectiveRecord
     */
    public PlayerObjectiveRecord() {
        super(PlayerObjective.PLAYER_OBJECTIVE);
    }

    /**
     * Create a detached, initialised PlayerObjectiveRecord
     */
    public PlayerObjectiveRecord(Integer id, String name, String threshold, Integer gameMissionId, Integer scaleId) {
        super(PlayerObjective.PLAYER_OBJECTIVE);

        setId(id);
        setName(name);
        setThreshold(threshold);
        setGameMissionId(gameMissionId);
        setScaleId(scaleId);
        resetChangedOnNotNull();
    }
}
