/*
 * This file is generated by jOOQ.
 */
package nl.gamedata.data.tables.records;


import nl.gamedata.data.tables.PrivateDashboard;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrivateDashboardRecord extends UpdatableRecordImpl<PrivateDashboardRecord> implements Record5<Integer, String, String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gamedata.private_dashboard.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gamedata.private_dashboard.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gamedata.private_dashboard.key</code>.
     */
    public void setKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gamedata.private_dashboard.key</code>.
     */
    public String getKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gamedata.private_dashboard.value</code>.
     */
    public void setValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gamedata.private_dashboard.value</code>.
     */
    public String getValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gamedata.private_dashboard.game_mission_id</code>.
     */
    public void setGameMissionId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>gamedata.private_dashboard.game_mission_id</code>.
     */
    public Integer getGameMissionId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>gamedata.private_dashboard.game_access_id</code>.
     */
    public void setGameAccessId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>gamedata.private_dashboard.game_access_id</code>.
     */
    public Integer getGameAccessId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PrivateDashboard.PRIVATE_DASHBOARD.ID;
    }

    @Override
    public Field<String> field2() {
        return PrivateDashboard.PRIVATE_DASHBOARD.KEY;
    }

    @Override
    public Field<String> field3() {
        return PrivateDashboard.PRIVATE_DASHBOARD.VALUE;
    }

    @Override
    public Field<Integer> field4() {
        return PrivateDashboard.PRIVATE_DASHBOARD.GAME_MISSION_ID;
    }

    @Override
    public Field<Integer> field5() {
        return PrivateDashboard.PRIVATE_DASHBOARD.GAME_ACCESS_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getKey();
    }

    @Override
    public String component3() {
        return getValue();
    }

    @Override
    public Integer component4() {
        return getGameMissionId();
    }

    @Override
    public Integer component5() {
        return getGameAccessId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getKey();
    }

    @Override
    public String value3() {
        return getValue();
    }

    @Override
    public Integer value4() {
        return getGameMissionId();
    }

    @Override
    public Integer value5() {
        return getGameAccessId();
    }

    @Override
    public PrivateDashboardRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PrivateDashboardRecord value2(String value) {
        setKey(value);
        return this;
    }

    @Override
    public PrivateDashboardRecord value3(String value) {
        setValue(value);
        return this;
    }

    @Override
    public PrivateDashboardRecord value4(Integer value) {
        setGameMissionId(value);
        return this;
    }

    @Override
    public PrivateDashboardRecord value5(Integer value) {
        setGameAccessId(value);
        return this;
    }

    @Override
    public PrivateDashboardRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PrivateDashboardRecord
     */
    public PrivateDashboardRecord() {
        super(PrivateDashboard.PRIVATE_DASHBOARD);
    }

    /**
     * Create a detached, initialised PrivateDashboardRecord
     */
    public PrivateDashboardRecord(Integer id, String key, String value, Integer gameMissionId, Integer gameAccessId) {
        super(PrivateDashboard.PRIVATE_DASHBOARD);

        setId(id);
        setKey(key);
        setValue(value);
        setGameMissionId(gameMissionId);
        setGameAccessId(gameAccessId);
        resetChangedOnNotNull();
    }
}
