/*
 * This file is generated by jOOQ.
 */
package nl.gamedata.data.tables.records;


import nl.gamedata.data.tables.SessionRole;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionRoleRecord extends UpdatableRecordImpl<SessionRoleRecord> implements Record6<Integer, Byte, Byte, Byte, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gamedata.session_role.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gamedata.session_role.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gamedata.session_role.view</code>.
     */
    public void setView(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>gamedata.session_role.view</code>.
     */
    public Byte getView() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>gamedata.session_role.edit</code>.
     */
    public void setEdit(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>gamedata.session_role.edit</code>.
     */
    public Byte getEdit() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>gamedata.session_role.create</code>.
     */
    public void setCreate(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>gamedata.session_role.create</code>.
     */
    public Byte getCreate() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>gamedata.session_role.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>gamedata.session_role.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>gamedata.session_role.game_session_id</code>.
     */
    public void setGameSessionId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>gamedata.session_role.game_session_id</code>.
     */
    public Integer getGameSessionId() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Byte, Byte, Byte, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Byte, Byte, Byte, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return SessionRole.SESSION_ROLE.ID;
    }

    @Override
    public Field<Byte> field2() {
        return SessionRole.SESSION_ROLE.VIEW;
    }

    @Override
    public Field<Byte> field3() {
        return SessionRole.SESSION_ROLE.EDIT;
    }

    @Override
    public Field<Byte> field4() {
        return SessionRole.SESSION_ROLE.CREATE;
    }

    @Override
    public Field<Integer> field5() {
        return SessionRole.SESSION_ROLE.USER_ID;
    }

    @Override
    public Field<Integer> field6() {
        return SessionRole.SESSION_ROLE.GAME_SESSION_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Byte component2() {
        return getView();
    }

    @Override
    public Byte component3() {
        return getEdit();
    }

    @Override
    public Byte component4() {
        return getCreate();
    }

    @Override
    public Integer component5() {
        return getUserId();
    }

    @Override
    public Integer component6() {
        return getGameSessionId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Byte value2() {
        return getView();
    }

    @Override
    public Byte value3() {
        return getEdit();
    }

    @Override
    public Byte value4() {
        return getCreate();
    }

    @Override
    public Integer value5() {
        return getUserId();
    }

    @Override
    public Integer value6() {
        return getGameSessionId();
    }

    @Override
    public SessionRoleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SessionRoleRecord value2(Byte value) {
        setView(value);
        return this;
    }

    @Override
    public SessionRoleRecord value3(Byte value) {
        setEdit(value);
        return this;
    }

    @Override
    public SessionRoleRecord value4(Byte value) {
        setCreate(value);
        return this;
    }

    @Override
    public SessionRoleRecord value5(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public SessionRoleRecord value6(Integer value) {
        setGameSessionId(value);
        return this;
    }

    @Override
    public SessionRoleRecord values(Integer value1, Byte value2, Byte value3, Byte value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SessionRoleRecord
     */
    public SessionRoleRecord() {
        super(SessionRole.SESSION_ROLE);
    }

    /**
     * Create a detached, initialised SessionRoleRecord
     */
    public SessionRoleRecord(Integer id, Byte view, Byte edit, Byte create, Integer userId, Integer gameSessionId) {
        super(SessionRole.SESSION_ROLE);

        setId(id);
        setView(view);
        setEdit(edit);
        setCreate(create);
        setUserId(userId);
        setGameSessionId(gameSessionId);
        resetChangedOnNotNull();
    }
}
