/*
 * This file is generated by jOOQ.
 */
package nl.gamedata.data.tables.records;


import nl.gamedata.data.tables.SessionRole;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionRoleRecord extends UpdatableRecordImpl<SessionRoleRecord> implements Record5<Integer, Byte, Byte, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gamedata.session_role.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gamedata.session_role.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gamedata.session_role.session_admin</code>.
     */
    public void setSessionAdmin(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>gamedata.session_role.session_admin</code>.
     */
    public Byte getSessionAdmin() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>gamedata.session_role.result_reader</code>.
     */
    public void setResultReader(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>gamedata.session_role.result_reader</code>.
     */
    public Byte getResultReader() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>gamedata.session_role.game_session_id</code>.
     */
    public void setGameSessionId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>gamedata.session_role.game_session_id</code>.
     */
    public Integer getGameSessionId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>gamedata.session_role.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>gamedata.session_role.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Byte, Byte, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Byte, Byte, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return SessionRole.SESSION_ROLE.ID;
    }

    @Override
    public Field<Byte> field2() {
        return SessionRole.SESSION_ROLE.SESSION_ADMIN;
    }

    @Override
    public Field<Byte> field3() {
        return SessionRole.SESSION_ROLE.RESULT_READER;
    }

    @Override
    public Field<Integer> field4() {
        return SessionRole.SESSION_ROLE.GAME_SESSION_ID;
    }

    @Override
    public Field<Integer> field5() {
        return SessionRole.SESSION_ROLE.USER_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Byte component2() {
        return getSessionAdmin();
    }

    @Override
    public Byte component3() {
        return getResultReader();
    }

    @Override
    public Integer component4() {
        return getGameSessionId();
    }

    @Override
    public Integer component5() {
        return getUserId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Byte value2() {
        return getSessionAdmin();
    }

    @Override
    public Byte value3() {
        return getResultReader();
    }

    @Override
    public Integer value4() {
        return getGameSessionId();
    }

    @Override
    public Integer value5() {
        return getUserId();
    }

    @Override
    public SessionRoleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SessionRoleRecord value2(Byte value) {
        setSessionAdmin(value);
        return this;
    }

    @Override
    public SessionRoleRecord value3(Byte value) {
        setResultReader(value);
        return this;
    }

    @Override
    public SessionRoleRecord value4(Integer value) {
        setGameSessionId(value);
        return this;
    }

    @Override
    public SessionRoleRecord value5(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public SessionRoleRecord values(Integer value1, Byte value2, Byte value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SessionRoleRecord
     */
    public SessionRoleRecord() {
        super(SessionRole.SESSION_ROLE);
    }

    /**
     * Create a detached, initialised SessionRoleRecord
     */
    public SessionRoleRecord(Integer id, Byte sessionAdmin, Byte resultReader, Integer gameSessionId, Integer userId) {
        super(SessionRole.SESSION_ROLE);

        setId(id);
        setSessionAdmin(sessionAdmin);
        setResultReader(resultReader);
        setGameSessionId(gameSessionId);
        setUserId(userId);
        resetChangedOnNotNull();
    }
}
