/*
 * This file is generated by jOOQ.
 */
package nl.gamedata.data.tables.records;


import nl.gamedata.data.tables.TemplateElement;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TemplateElementRecord extends UpdatableRecordImpl<TemplateElementRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gamedata.template_element.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gamedata.template_element.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gamedata.template_element.dashboard_element_id</code>.
     */
    public void setDashboardElementId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>gamedata.template_element.dashboard_element_id</code>.
     */
    public Integer getDashboardElementId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>gamedata.template_element.dashboard_template_id</code>.
     */
    public void setDashboardTemplateId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>gamedata.template_element.dashboard_template_id</code>.
     */
    public Integer getDashboardTemplateId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TemplateElementRecord
     */
    public TemplateElementRecord() {
        super(TemplateElement.TEMPLATE_ELEMENT);
    }

    /**
     * Create a detached, initialised TemplateElementRecord
     */
    public TemplateElementRecord(Integer id, Integer dashboardElementId, Integer dashboardTemplateId) {
        super(TemplateElement.TEMPLATE_ELEMENT);

        setId(id);
        setDashboardElementId(dashboardElementId);
        setDashboardTemplateId(dashboardTemplateId);
        resetChangedOnNotNull();
    }
}
