/*
 * This file is generated by jOOQ.
 */
package nl.gamedata.data.tables.records;


import nl.gamedata.data.tables.Token;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TokenRecord extends UpdatableRecordImpl<TokenRecord> implements Record7<Integer, String, String, Integer, Integer, Byte, Byte> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gamedata.token.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gamedata.token.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gamedata.token.value</code>.
     */
    public void setValue(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gamedata.token.value</code>.
     */
    public String getValue() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gamedata.token.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gamedata.token.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gamedata.token.game_id</code>.
     */
    public void setGameId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>gamedata.token.game_id</code>.
     */
    public Integer getGameId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>gamedata.token.organization_id</code>.
     */
    public void setOrganizationId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>gamedata.token.organization_id</code>.
     */
    public Integer getOrganizationId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>gamedata.token.data_writer</code>.
     */
    public void setDataWriter(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>gamedata.token.data_writer</code>.
     */
    public Byte getDataWriter() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>gamedata.token.result_reader</code>.
     */
    public void setResultReader(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>gamedata.token.result_reader</code>.
     */
    public Byte getResultReader() {
        return (Byte) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, Integer, Integer, Byte, Byte> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, Integer, Integer, Byte, Byte> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Token.TOKEN.ID;
    }

    @Override
    public Field<String> field2() {
        return Token.TOKEN.VALUE;
    }

    @Override
    public Field<String> field3() {
        return Token.TOKEN.NAME;
    }

    @Override
    public Field<Integer> field4() {
        return Token.TOKEN.GAME_ID;
    }

    @Override
    public Field<Integer> field5() {
        return Token.TOKEN.ORGANIZATION_ID;
    }

    @Override
    public Field<Byte> field6() {
        return Token.TOKEN.DATA_WRITER;
    }

    @Override
    public Field<Byte> field7() {
        return Token.TOKEN.RESULT_READER;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getValue();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Integer component4() {
        return getGameId();
    }

    @Override
    public Integer component5() {
        return getOrganizationId();
    }

    @Override
    public Byte component6() {
        return getDataWriter();
    }

    @Override
    public Byte component7() {
        return getResultReader();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getValue();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public Integer value4() {
        return getGameId();
    }

    @Override
    public Integer value5() {
        return getOrganizationId();
    }

    @Override
    public Byte value6() {
        return getDataWriter();
    }

    @Override
    public Byte value7() {
        return getResultReader();
    }

    @Override
    public TokenRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TokenRecord value2(String value) {
        setValue(value);
        return this;
    }

    @Override
    public TokenRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public TokenRecord value4(Integer value) {
        setGameId(value);
        return this;
    }

    @Override
    public TokenRecord value5(Integer value) {
        setOrganizationId(value);
        return this;
    }

    @Override
    public TokenRecord value6(Byte value) {
        setDataWriter(value);
        return this;
    }

    @Override
    public TokenRecord value7(Byte value) {
        setResultReader(value);
        return this;
    }

    @Override
    public TokenRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5, Byte value6, Byte value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TokenRecord
     */
    public TokenRecord() {
        super(Token.TOKEN);
    }

    /**
     * Create a detached, initialised TokenRecord
     */
    public TokenRecord(Integer id, String value, String name, Integer gameId, Integer organizationId, Byte dataWriter, Byte resultReader) {
        super(Token.TOKEN);

        setId(id);
        setValue(value);
        setName(name);
        setGameId(gameId);
        setOrganizationId(organizationId);
        setDataWriter(dataWriter);
        setResultReader(resultReader);
        resetChangedOnNotNull();
    }
}
