/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.housinggame.data;


import nl.tudelft.simulation.housinggame.data.tables.DashboardSetting;
import nl.tudelft.simulation.housinggame.data.tables.GameMission;
import nl.tudelft.simulation.housinggame.data.tables.GameRole;
import nl.tudelft.simulation.housinggame.data.tables.GameSession;
import nl.tudelft.simulation.housinggame.data.tables.Group;
import nl.tudelft.simulation.housinggame.data.tables.GroupEvent;
import nl.tudelft.simulation.housinggame.data.tables.GroupLogdata;
import nl.tudelft.simulation.housinggame.data.tables.GroupScore;
import nl.tudelft.simulation.housinggame.data.tables.MissionEvent;
import nl.tudelft.simulation.housinggame.data.tables.MissionLogdata;
import nl.tudelft.simulation.housinggame.data.tables.Player;
import nl.tudelft.simulation.housinggame.data.tables.PlayerEvent;
import nl.tudelft.simulation.housinggame.data.tables.PlayerLogdata;
import nl.tudelft.simulation.housinggame.data.tables.PlayerScore;
import nl.tudelft.simulation.housinggame.data.tables.SessionRole;
import nl.tudelft.simulation.housinggame.data.tables.User;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in gamedata.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DASHBOARD_SETTING_FK_DASHBOARD_GAME1_IDX = Internal.createIndex(DSL.name("fk_dashboard_game1_idx"), DashboardSetting.DASHBOARD_SETTING, new OrderField[] { DashboardSetting.DASHBOARD_SETTING.GAME_ID }, false);
    public static final Index GROUP_FK_GAMEGROUP_GAMESESSION1_IDX = Internal.createIndex(DSL.name("fk_gamegroup_gamesession1_idx"), Group.GROUP, new OrderField[] { Group.GROUP.GAMESESSION_ID }, false);
    public static final Index GAME_MISSION_FK_GAMESESSION_GAMEVERSION1_IDX = Internal.createIndex(DSL.name("fk_gamesession_gameversion1_idx"), GameMission.GAME_MISSION, new OrderField[] { GameMission.GAME_MISSION.GAMEVERSION_ID }, false);
    public static final Index PLAYER_FK_GAMEUSER_GAMEGROUP1_IDX = Internal.createIndex(DSL.name("fk_gameuser_gamegroup1_idx"), Player.PLAYER, new OrderField[] { Player.PLAYER.GAMEGROUP_ID }, false);
    public static final Index PLAYER_FK_GAMEUSER_GAMESESSION1_IDX = Internal.createIndex(DSL.name("fk_gameuser_gamesession1_idx"), Player.PLAYER, new OrderField[] { Player.PLAYER.GAMESESSION_ID }, false);
    public static final Index GAME_SESSION_FK_GAMEVERSION_GAME1_IDX = Internal.createIndex(DSL.name("fk_gameversion_game1_idx"), GameSession.GAME_SESSION, new OrderField[] { GameSession.GAME_SESSION.GAME_ID }, false);
    public static final Index GROUP_EVENT_FK_GROUPEVENT_GROUP1_IDX = Internal.createIndex(DSL.name("fk_groupevent_group1_idx"), GroupEvent.GROUP_EVENT, new OrderField[] { GroupEvent.GROUP_EVENT.GROUP_ID }, false);
    public static final Index GROUP_LOGDATA_FK_GROUPLOGDATA_GROUP1_IDX = Internal.createIndex(DSL.name("fk_grouplogdata_group1_idx"), GroupLogdata.GROUP_LOGDATA, new OrderField[] { GroupLogdata.GROUP_LOGDATA.GROUP_ID }, false);
    public static final Index GROUP_SCORE_FK_GROUPSCORE_GROUP1_IDX = Internal.createIndex(DSL.name("fk_groupscore_group1_idx"), GroupScore.GROUP_SCORE, new OrderField[] { GroupScore.GROUP_SCORE.GROUP_ID }, false);
    public static final Index PLAYER_EVENT_FK_PLAYEREVENT_PLAYER1_IDX = Internal.createIndex(DSL.name("fk_playerevent_player1_idx"), PlayerEvent.PLAYER_EVENT, new OrderField[] { PlayerEvent.PLAYER_EVENT.PLAYER_ID }, false);
    public static final Index PLAYER_LOGDATA_FK_PLAYERLOGDATA_PLAYER1_IDX = Internal.createIndex(DSL.name("fk_playerlogdata_player1_idx"), PlayerLogdata.PLAYER_LOGDATA, new OrderField[] { PlayerLogdata.PLAYER_LOGDATA.PLAYER_ID }, false);
    public static final Index PLAYER_SCORE_FK_PLAYERSCORE_PLAYER1_IDX = Internal.createIndex(DSL.name("fk_playerscore_player1_idx"), PlayerScore.PLAYER_SCORE, new OrderField[] { PlayerScore.PLAYER_SCORE.PLAYER_ID }, false);
    public static final Index SESSION_ROLE_FK_SESSION_ROLE_GAME_SESSION1_IDX = Internal.createIndex(DSL.name("fk_session_role_game_session1_idx"), SessionRole.SESSION_ROLE, new OrderField[] { SessionRole.SESSION_ROLE.GAME_SESSION_ID }, false);
    public static final Index MISSION_EVENT_FK_SESSIONEVENT_GAMESESSION1_IDX = Internal.createIndex(DSL.name("fk_sessionevent_gamesession1_idx"), MissionEvent.MISSION_EVENT, new OrderField[] { MissionEvent.MISSION_EVENT.GAMESESSION_ID }, false);
    public static final Index MISSION_LOGDATA_FK_SESSIONLOGDATA_GAMESESSION1_IDX = Internal.createIndex(DSL.name("fk_sessionlogdata_gamesession1_idx"), MissionLogdata.MISSION_LOGDATA, new OrderField[] { MissionLogdata.MISSION_LOGDATA.GAMESESSION_ID }, false);
    public static final Index SESSION_ROLE_FK_SESSIONROLE_ROLE1_IDX = Internal.createIndex(DSL.name("fk_sessionrole_role1_idx"), SessionRole.SESSION_ROLE, new OrderField[] { SessionRole.SESSION_ROLE.ROLE_ID }, false);
    public static final Index SESSION_ROLE_FK_SESSIONROLE_USER1_IDX = Internal.createIndex(DSL.name("fk_sessionrole_user1_idx"), SessionRole.SESSION_ROLE, new OrderField[] { SessionRole.SESSION_ROLE.USER_ID }, false);
    public static final Index USER_FK_USER_ORGANIZATION1_IDX = Internal.createIndex(DSL.name("fk_user_organization1_idx"), User.USER, new OrderField[] { User.USER.ORGANIZATION_ID }, false);
    public static final Index USER_FK_USER_ROLE1_IDX = Internal.createIndex(DSL.name("fk_user_role1_idx"), User.USER, new OrderField[] { User.USER.ROLE_ID }, false);
    public static final Index GAME_ROLE_FK_USERROLE_GAME1_IDX = Internal.createIndex(DSL.name("fk_userrole_game1_idx"), GameRole.GAME_ROLE, new OrderField[] { GameRole.GAME_ROLE.GAME_ID }, false);
    public static final Index GAME_ROLE_FK_USERROLE_ROLE1_IDX = Internal.createIndex(DSL.name("fk_userrole_role1_idx"), GameRole.GAME_ROLE, new OrderField[] { GameRole.GAME_ROLE.ROLE_ID }, false);
    public static final Index GAME_ROLE_FK_USERROLE_USER_IDX = Internal.createIndex(DSL.name("fk_userrole_user_idx"), GameRole.GAME_ROLE, new OrderField[] { GameRole.GAME_ROLE.USER_ID }, false);
}
