/*
 * This file is generated by jOOQ.
 */
package nl.gamedata.data;


import nl.gamedata.data.tables.DashboardSetting;
import nl.gamedata.data.tables.GameMission;
import nl.gamedata.data.tables.GameRole;
import nl.gamedata.data.tables.GameSession;
import nl.gamedata.data.tables.GameVersion;
import nl.gamedata.data.tables.Group;
import nl.gamedata.data.tables.GroupEvent;
import nl.gamedata.data.tables.GroupLogdata;
import nl.gamedata.data.tables.GroupRole;
import nl.gamedata.data.tables.GroupScore;
import nl.gamedata.data.tables.MissionEvent;
import nl.gamedata.data.tables.MissionLogdata;
import nl.gamedata.data.tables.Player;
import nl.gamedata.data.tables.PlayerAttempt;
import nl.gamedata.data.tables.PlayerEvent;
import nl.gamedata.data.tables.PlayerLogdata;
import nl.gamedata.data.tables.PlayerScore;
import nl.gamedata.data.tables.Token;
import nl.gamedata.data.tables.User;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in gamedata.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DASHBOARD_SETTING_FK_DASHBOARD_GAME1_IDX = Internal.createIndex(DSL.name("fk_dashboard_game1_idx"), DashboardSetting.DASHBOARD_SETTING, new OrderField[] { DashboardSetting.DASHBOARD_SETTING.GAME_ID }, false);
    public static final Index GAME_MISSION_FK_GAME_MISSION_GAME_VERSION1_IDX = Internal.createIndex(DSL.name("fk_game_mission_game_version1_idx"), GameMission.GAME_MISSION, new OrderField[] { GameMission.GAME_MISSION.GAME_VERSION_ID }, false);
    public static final Index GAME_SESSION_FK_GAME_SESSION_GAME_VERSION1_IDX = Internal.createIndex(DSL.name("fk_game_session_game_version1_idx"), GameSession.GAME_SESSION, new OrderField[] { GameSession.GAME_SESSION.GAME_VERSION_ID }, false);
    public static final Index GAME_VERSION_FK_GAME_VERSION_GAME1_IDX = Internal.createIndex(DSL.name("fk_game_version_game1_idx"), GameVersion.GAME_VERSION, new OrderField[] { GameVersion.GAME_VERSION.GAME_ID }, false);
    public static final Index GROUP_FK_GROUP_GAME_SESSION1_IDX = Internal.createIndex(DSL.name("fk_group_game_session1_idx"), Group.GROUP, new OrderField[] { Group.GROUP.GAME_SESSION_ID }, false);
    public static final Index GROUP_ROLE_FK_GROUP_ROLE_GROUP1_IDX = Internal.createIndex(DSL.name("fk_group_role_group1_idx"), GroupRole.GROUP_ROLE, new OrderField[] { GroupRole.GROUP_ROLE.GROUP_ID }, false);
    public static final Index GROUP_EVENT_FK_GROUPEVENT_GROUP1_IDX = Internal.createIndex(DSL.name("fk_groupevent_group1_idx"), GroupEvent.GROUP_EVENT, new OrderField[] { GroupEvent.GROUP_EVENT.GROUP_ID }, false);
    public static final Index GROUP_LOGDATA_FK_GROUPLOGDATA_GROUP1_IDX = Internal.createIndex(DSL.name("fk_grouplogdata_group1_idx"), GroupLogdata.GROUP_LOGDATA, new OrderField[] { GroupLogdata.GROUP_LOGDATA.GROUP_ID }, false);
    public static final Index GROUP_SCORE_FK_GROUPSCORE_GROUP1_IDX = Internal.createIndex(DSL.name("fk_groupscore_group1_idx"), GroupScore.GROUP_SCORE, new OrderField[] { GroupScore.GROUP_SCORE.GROUP_ID }, false);
    public static final Index PLAYER_ATTEMPT_FK_PLAYER_ATTEMPT_GAME_MISSION1_IDX = Internal.createIndex(DSL.name("fk_player_attempt_game_mission1_idx"), PlayerAttempt.PLAYER_ATTEMPT, new OrderField[] { PlayerAttempt.PLAYER_ATTEMPT.GAME_MISSION_ID }, false);
    public static final Index PLAYER_ATTEMPT_FK_PLAYER_ATTEMPT_GAME_SESSION1_IDX = Internal.createIndex(DSL.name("fk_player_attempt_game_session1_idx"), PlayerAttempt.PLAYER_ATTEMPT, new OrderField[] { PlayerAttempt.PLAYER_ATTEMPT.GAME_SESSION_ID }, false);
    public static final Index PLAYER_ATTEMPT_FK_PLAYER_ATTEMPT_PLAYER1_IDX = Internal.createIndex(DSL.name("fk_player_attempt_player1_idx"), PlayerAttempt.PLAYER_ATTEMPT, new OrderField[] { PlayerAttempt.PLAYER_ATTEMPT.PLAYER_ID }, false);
    public static final Index PLAYER_EVENT_FK_PLAYER_EVENT_PLAYER_ATTEMPT1_IDX = Internal.createIndex(DSL.name("fk_player_event_player_attempt1_idx"), PlayerEvent.PLAYER_EVENT, new OrderField[] { PlayerEvent.PLAYER_EVENT.PLAYER_ATTEMPT_ID }, false);
    public static final Index PLAYER_FK_PLAYER_GAME_SESSION1_IDX = Internal.createIndex(DSL.name("fk_player_game_session1_idx"), Player.PLAYER, new OrderField[] { Player.PLAYER.GAME_SESSION_ID }, false);
    public static final Index PLAYER_FK_PLAYER_GROUP_ROLE1_IDX = Internal.createIndex(DSL.name("fk_player_group_role1_idx"), Player.PLAYER, new OrderField[] { Player.PLAYER.GROUP_ROLE_ID }, false);
    public static final Index PLAYER_LOGDATA_FK_PLAYER_LOGDATA_PLAYER_ATTEMPT1_IDX = Internal.createIndex(DSL.name("fk_player_logdata_player_attempt1_idx"), PlayerLogdata.PLAYER_LOGDATA, new OrderField[] { PlayerLogdata.PLAYER_LOGDATA.PLAYER_ATTEMPT_ID }, false);
    public static final Index PLAYER_SCORE_FK_PLAYER_SCORE_PLAYER_ATTEMPT1_IDX = Internal.createIndex(DSL.name("fk_player_score_player_attempt1_idx"), PlayerScore.PLAYER_SCORE, new OrderField[] { PlayerScore.PLAYER_SCORE.PLAYER_ATTEMPT_ID }, false);
    public static final Index MISSION_EVENT_FK_SESSIONEVENT_GAMESESSION1_IDX = Internal.createIndex(DSL.name("fk_sessionevent_gamesession1_idx"), MissionEvent.MISSION_EVENT, new OrderField[] { MissionEvent.MISSION_EVENT.GAMESESSION_ID }, false);
    public static final Index MISSION_LOGDATA_FK_SESSIONLOGDATA_GAMESESSION1_IDX = Internal.createIndex(DSL.name("fk_sessionlogdata_gamesession1_idx"), MissionLogdata.MISSION_LOGDATA, new OrderField[] { MissionLogdata.MISSION_LOGDATA.GAMESESSION_ID }, false);
    public static final Index TOKEN_FK_TOKEN_GAME1_IDX = Internal.createIndex(DSL.name("fk_token_game1_idx"), Token.TOKEN, new OrderField[] { Token.TOKEN.GAME_ID }, false);
    public static final Index TOKEN_FK_TOKEN_ORGANIZATION1_IDX = Internal.createIndex(DSL.name("fk_token_organization1_idx"), Token.TOKEN, new OrderField[] { Token.TOKEN.ORGANIZATION_ID }, false);
    public static final Index USER_FK_USER_ORGANIZATION1_IDX = Internal.createIndex(DSL.name("fk_user_organization1_idx"), User.USER, new OrderField[] { User.USER.ORGANIZATION_ID }, false);
    public static final Index GAME_ROLE_FK_USERROLE_GAME1_IDX = Internal.createIndex(DSL.name("fk_userrole_game1_idx"), GameRole.GAME_ROLE, new OrderField[] { GameRole.GAME_ROLE.GAME_ID }, false);
    public static final Index GAME_ROLE_FK_USERROLE_USER_IDX = Internal.createIndex(DSL.name("fk_userrole_user_idx"), GameRole.GAME_ROLE, new OrderField[] { GameRole.GAME_ROLE.USER_ID }, false);
}
