/*
 * This file is generated by jOOQ.
 */
package nl.gamedata.data.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import nl.gamedata.data.Gamedata;
import nl.gamedata.data.Indexes;
import nl.gamedata.data.Keys;
import nl.gamedata.data.tables.DashboardTemplate.DashboardTemplatePath;
import nl.gamedata.data.tables.User.UserPath;
import nl.gamedata.data.tables.records.DashboardRoleRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DashboardRole extends TableImpl<DashboardRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>gamedata.dashboard_role</code>
     */
    public static final DashboardRole DASHBOARD_ROLE = new DashboardRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DashboardRoleRecord> getRecordType() {
        return DashboardRoleRecord.class;
    }

    /**
     * The column <code>gamedata.dashboard_role.id</code>.
     */
    public final TableField<DashboardRoleRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>gamedata.dashboard_role.view</code>.
     */
    public final TableField<DashboardRoleRecord, Byte> VIEW = createField(DSL.name("view"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>gamedata.dashboard_role.edit</code>.
     */
    public final TableField<DashboardRoleRecord, Byte> EDIT = createField(DSL.name("edit"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>gamedata.dashboard_role.user_id</code>.
     */
    public final TableField<DashboardRoleRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>gamedata.dashboard_role.dashboard_template_id</code>.
     */
    public final TableField<DashboardRoleRecord, Integer> DASHBOARD_TEMPLATE_ID = createField(DSL.name("dashboard_template_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private DashboardRole(Name alias, Table<DashboardRoleRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DashboardRole(Name alias, Table<DashboardRoleRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>gamedata.dashboard_role</code> table reference
     */
    public DashboardRole(String alias) {
        this(DSL.name(alias), DASHBOARD_ROLE);
    }

    /**
     * Create an aliased <code>gamedata.dashboard_role</code> table reference
     */
    public DashboardRole(Name alias) {
        this(alias, DASHBOARD_ROLE);
    }

    /**
     * Create a <code>gamedata.dashboard_role</code> table reference
     */
    public DashboardRole() {
        this(DSL.name("dashboard_role"), null);
    }

    public <O extends Record> DashboardRole(Table<O> path, ForeignKey<O, DashboardRoleRecord> childPath, InverseForeignKey<O, DashboardRoleRecord> parentPath) {
        super(path, childPath, parentPath, DASHBOARD_ROLE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class DashboardRolePath extends DashboardRole implements Path<DashboardRoleRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> DashboardRolePath(Table<O> path, ForeignKey<O, DashboardRoleRecord> childPath, InverseForeignKey<O, DashboardRoleRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private DashboardRolePath(Name alias, Table<DashboardRoleRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public DashboardRolePath as(String alias) {
            return new DashboardRolePath(DSL.name(alias), this);
        }

        @Override
        public DashboardRolePath as(Name alias) {
            return new DashboardRolePath(alias, this);
        }

        @Override
        public DashboardRolePath as(Table<?> alias) {
            return new DashboardRolePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Gamedata.GAMEDATA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.DASHBOARD_ROLE_FK_DASHBOARD_ROLE_DASHBOARD_TEMPLATE1_IDX, Indexes.DASHBOARD_ROLE_FK_DASHBOARD_ROLE_USER1_IDX);
    }

    @Override
    public Identity<DashboardRoleRecord, Integer> getIdentity() {
        return (Identity<DashboardRoleRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<DashboardRoleRecord> getPrimaryKey() {
        return Keys.KEY_DASHBOARD_ROLE_PRIMARY;
    }

    @Override
    public List<UniqueKey<DashboardRoleRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_DASHBOARD_ROLE_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<DashboardRoleRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_DASHBOARD_ROLE_DASHBOARD_TEMPLATE1, Keys.FK_DASHBOARD_ROLE_USER1);
    }

    private transient DashboardTemplatePath _dashboardTemplate;

    /**
     * Get the implicit join path to the
     * <code>gamedata.dashboard_template</code> table.
     */
    public DashboardTemplatePath dashboardTemplate() {
        if (_dashboardTemplate == null)
            _dashboardTemplate = new DashboardTemplatePath(this, Keys.FK_DASHBOARD_ROLE_DASHBOARD_TEMPLATE1, null);

        return _dashboardTemplate;
    }

    private transient UserPath _user;

    /**
     * Get the implicit join path to the <code>gamedata.user</code> table.
     */
    public UserPath user() {
        if (_user == null)
            _user = new UserPath(this, Keys.FK_DASHBOARD_ROLE_USER1, null);

        return _user;
    }

    @Override
    public DashboardRole as(String alias) {
        return new DashboardRole(DSL.name(alias), this);
    }

    @Override
    public DashboardRole as(Name alias) {
        return new DashboardRole(alias, this);
    }

    @Override
    public DashboardRole as(Table<?> alias) {
        return new DashboardRole(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DashboardRole rename(String name) {
        return new DashboardRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DashboardRole rename(Name name) {
        return new DashboardRole(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DashboardRole rename(Table<?> name) {
        return new DashboardRole(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DashboardRole where(Condition condition) {
        return new DashboardRole(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DashboardRole where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DashboardRole where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DashboardRole where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DashboardRole where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DashboardRole where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DashboardRole where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DashboardRole where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DashboardRole whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DashboardRole whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
