/*
 * This file is generated by jOOQ.
 */
package nl.gamedata.data.tables;


import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import nl.gamedata.data.Gamedata;
import nl.gamedata.data.Indexes;
import nl.gamedata.data.Keys;
import nl.gamedata.data.tables.records.DashboardTemplateRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function8;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DashboardTemplate extends TableImpl<DashboardTemplateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>gamedata.dashboard_template</code>
     */
    public static final DashboardTemplate DASHBOARD_TEMPLATE = new DashboardTemplate();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DashboardTemplateRecord> getRecordType() {
        return DashboardTemplateRecord.class;
    }

    /**
     * The column <code>gamedata.dashboard_template.id</code>.
     */
    public final TableField<DashboardTemplateRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>gamedata.dashboard_template.name</code>.
     */
    public final TableField<DashboardTemplateRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>gamedata.dashboard_template.description</code>.
     */
    public final TableField<DashboardTemplateRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>gamedata.dashboard_template.private</code>.
     */
    public final TableField<DashboardTemplateRecord, Byte> PRIVATE = createField(DSL.name("private"), SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>gamedata.dashboard_template.game_version_id</code>.
     */
    public final TableField<DashboardTemplateRecord, Integer> GAME_VERSION_ID = createField(DSL.name("game_version_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>gamedata.dashboard_template.game_mission_id</code>.
     */
    public final TableField<DashboardTemplateRecord, Integer> GAME_MISSION_ID = createField(DSL.name("game_mission_id"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>gamedata.dashboard_template.organization_game_id</code>.
     */
    public final TableField<DashboardTemplateRecord, Integer> ORGANIZATION_GAME_ID = createField(DSL.name("organization_game_id"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>gamedata.dashboard_template.dashboard_layout_id</code>.
     */
    public final TableField<DashboardTemplateRecord, Integer> DASHBOARD_LAYOUT_ID = createField(DSL.name("dashboard_layout_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private DashboardTemplate(Name alias, Table<DashboardTemplateRecord> aliased) {
        this(alias, aliased, null);
    }

    private DashboardTemplate(Name alias, Table<DashboardTemplateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>gamedata.dashboard_template</code> table
     * reference
     */
    public DashboardTemplate(String alias) {
        this(DSL.name(alias), DASHBOARD_TEMPLATE);
    }

    /**
     * Create an aliased <code>gamedata.dashboard_template</code> table
     * reference
     */
    public DashboardTemplate(Name alias) {
        this(alias, DASHBOARD_TEMPLATE);
    }

    /**
     * Create a <code>gamedata.dashboard_template</code> table reference
     */
    public DashboardTemplate() {
        this(DSL.name("dashboard_template"), null);
    }

    public <O extends Record> DashboardTemplate(Table<O> child, ForeignKey<O, DashboardTemplateRecord> key) {
        super(child, key, DASHBOARD_TEMPLATE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Gamedata.GAMEDATA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.DASHBOARD_TEMPLATE_FK_DASHBOARD_TEMPLATE_DASHBOARD_LAYOUT1_IDX, Indexes.DASHBOARD_TEMPLATE_FK_DASHBOARD_TEMPLATE_GAME_VERSION1_IDX, Indexes.DASHBOARD_TEMPLATE_FK_DASHBOARD_TEMPLATE_ORGANIZATION_GAME1_IDX, Indexes.DASHBOARD_TEMPLATE_FK_PRIVATE_DASHBOARD_GAME_MISSION1_IDX);
    }

    @Override
    public Identity<DashboardTemplateRecord, Integer> getIdentity() {
        return (Identity<DashboardTemplateRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<DashboardTemplateRecord> getPrimaryKey() {
        return Keys.KEY_DASHBOARD_TEMPLATE_PRIMARY;
    }

    @Override
    public List<UniqueKey<DashboardTemplateRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_DASHBOARD_TEMPLATE_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<DashboardTemplateRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_DASHBOARD_TEMPLATE_GAME_VERSION1, Keys.FK_PRIVATE_DASHBOARD_GAME_MISSION1, Keys.FK_DASHBOARD_TEMPLATE_ORGANIZATION_GAME1, Keys.FK_DASHBOARD_TEMPLATE_DASHBOARD_LAYOUT1);
    }

    private transient GameVersion _gameVersion;
    private transient GameMission _gameMission;
    private transient OrganizationGame _organizationGame;
    private transient DashboardLayout _dashboardLayout;

    /**
     * Get the implicit join path to the <code>gamedata.game_version</code>
     * table.
     */
    public GameVersion gameVersion() {
        if (_gameVersion == null)
            _gameVersion = new GameVersion(this, Keys.FK_DASHBOARD_TEMPLATE_GAME_VERSION1);

        return _gameVersion;
    }

    /**
     * Get the implicit join path to the <code>gamedata.game_mission</code>
     * table.
     */
    public GameMission gameMission() {
        if (_gameMission == null)
            _gameMission = new GameMission(this, Keys.FK_PRIVATE_DASHBOARD_GAME_MISSION1);

        return _gameMission;
    }

    /**
     * Get the implicit join path to the <code>gamedata.organization_game</code>
     * table.
     */
    public OrganizationGame organizationGame() {
        if (_organizationGame == null)
            _organizationGame = new OrganizationGame(this, Keys.FK_DASHBOARD_TEMPLATE_ORGANIZATION_GAME1);

        return _organizationGame;
    }

    /**
     * Get the implicit join path to the <code>gamedata.dashboard_layout</code>
     * table.
     */
    public DashboardLayout dashboardLayout() {
        if (_dashboardLayout == null)
            _dashboardLayout = new DashboardLayout(this, Keys.FK_DASHBOARD_TEMPLATE_DASHBOARD_LAYOUT1);

        return _dashboardLayout;
    }

    @Override
    public DashboardTemplate as(String alias) {
        return new DashboardTemplate(DSL.name(alias), this);
    }

    @Override
    public DashboardTemplate as(Name alias) {
        return new DashboardTemplate(alias, this);
    }

    @Override
    public DashboardTemplate as(Table<?> alias) {
        return new DashboardTemplate(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DashboardTemplate rename(String name) {
        return new DashboardTemplate(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DashboardTemplate rename(Name name) {
        return new DashboardTemplate(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DashboardTemplate rename(Table<?> name) {
        return new DashboardTemplate(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, Byte, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function8<? super Integer, ? super String, ? super String, ? super Byte, ? super Integer, ? super Integer, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function8<? super Integer, ? super String, ? super String, ? super Byte, ? super Integer, ? super Integer, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
