/*
 * This file is generated by jOOQ.
 */
package nl.gamedata.data.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import nl.gamedata.data.Gamedata;
import nl.gamedata.data.Indexes;
import nl.gamedata.data.Keys;
import nl.gamedata.data.tables.records.MissionActionRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function10;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MissionAction extends TableImpl<MissionActionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>gamedata.mission_action</code>
     */
    public static final MissionAction MISSION_ACTION = new MissionAction();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MissionActionRecord> getRecordType() {
        return MissionActionRecord.class;
    }

    /**
     * The column <code>gamedata.mission_action.id</code>.
     */
    public final TableField<MissionActionRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>gamedata.mission_action.type</code>.
     */
    public final TableField<MissionActionRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>gamedata.mission_action.key</code>.
     */
    public final TableField<MissionActionRecord, String> KEY = createField(DSL.name("key"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>gamedata.mission_action.value</code>.
     */
    public final TableField<MissionActionRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>gamedata.mission_action.timestamp</code>.
     */
    public final TableField<MissionActionRecord, LocalDateTime> TIMESTAMP = createField(DSL.name("timestamp"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>gamedata.mission_action.status</code>.
     */
    public final TableField<MissionActionRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(45).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>gamedata.mission_action.round</code>.
     */
    public final TableField<MissionActionRecord, String> ROUND = createField(DSL.name("round"), SQLDataType.VARCHAR(16).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>gamedata.mission_action.game_time</code>.
     */
    public final TableField<MissionActionRecord, String> GAME_TIME = createField(DSL.name("game_time"), SQLDataType.VARCHAR(45).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>gamedata.mission_action.grouping_code</code>.
     */
    public final TableField<MissionActionRecord, String> GROUPING_CODE = createField(DSL.name("grouping_code"), SQLDataType.VARCHAR(45).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>gamedata.mission_action.gamesession_id</code>.
     */
    public final TableField<MissionActionRecord, Integer> GAMESESSION_ID = createField(DSL.name("gamesession_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private MissionAction(Name alias, Table<MissionActionRecord> aliased) {
        this(alias, aliased, null);
    }

    private MissionAction(Name alias, Table<MissionActionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>gamedata.mission_action</code> table reference
     */
    public MissionAction(String alias) {
        this(DSL.name(alias), MISSION_ACTION);
    }

    /**
     * Create an aliased <code>gamedata.mission_action</code> table reference
     */
    public MissionAction(Name alias) {
        this(alias, MISSION_ACTION);
    }

    /**
     * Create a <code>gamedata.mission_action</code> table reference
     */
    public MissionAction() {
        this(DSL.name("mission_action"), null);
    }

    public <O extends Record> MissionAction(Table<O> child, ForeignKey<O, MissionActionRecord> key) {
        super(child, key, MISSION_ACTION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Gamedata.GAMEDATA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MISSION_ACTION_FK_SESSIONLOGDATA_GAMESESSION1_IDX);
    }

    @Override
    public Identity<MissionActionRecord, Integer> getIdentity() {
        return (Identity<MissionActionRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<MissionActionRecord> getPrimaryKey() {
        return Keys.KEY_MISSION_ACTION_PRIMARY;
    }

    @Override
    public List<UniqueKey<MissionActionRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_MISSION_ACTION_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<MissionActionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_SESSIONLOGDATA_GAMESESSION1);
    }

    private transient GameMission _gameMission;

    /**
     * Get the implicit join path to the <code>gamedata.game_mission</code>
     * table.
     */
    public GameMission gameMission() {
        if (_gameMission == null)
            _gameMission = new GameMission(this, Keys.FK_SESSIONLOGDATA_GAMESESSION1);

        return _gameMission;
    }

    @Override
    public MissionAction as(String alias) {
        return new MissionAction(DSL.name(alias), this);
    }

    @Override
    public MissionAction as(Name alias) {
        return new MissionAction(alias, this);
    }

    @Override
    public MissionAction as(Table<?> alias) {
        return new MissionAction(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MissionAction rename(String name) {
        return new MissionAction(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MissionAction rename(Name name) {
        return new MissionAction(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MissionAction rename(Table<?> name) {
        return new MissionAction(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, String, String, LocalDateTime, String, String, String, String, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function10<? super Integer, ? super String, ? super String, ? super String, ? super LocalDateTime, ? super String, ? super String, ? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function10<? super Integer, ? super String, ? super String, ? super String, ? super LocalDateTime, ? super String, ? super String, ? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
