/*
 * This file is generated by jOOQ.
 */
package nl.gamedata.data.tables;


import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import nl.gamedata.data.Gamedata;
import nl.gamedata.data.Indexes;
import nl.gamedata.data.Keys;
import nl.gamedata.data.tables.records.OrganizationGameRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrganizationGame extends TableImpl<OrganizationGameRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>gamedata.organization_game</code>
     */
    public static final OrganizationGame ORGANIZATION_GAME = new OrganizationGame();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrganizationGameRecord> getRecordType() {
        return OrganizationGameRecord.class;
    }

    /**
     * The column <code>gamedata.organization_game.id</code>.
     */
    public final TableField<OrganizationGameRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>gamedata.organization_game.name</code>.
     */
    public final TableField<OrganizationGameRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>gamedata.organization_game.token_forced</code>.
     */
    public final TableField<OrganizationGameRecord, Byte> TOKEN_FORCED = createField(DSL.name("token_forced"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>gamedata.organization_game.anonymous_sessions</code>.
     */
    public final TableField<OrganizationGameRecord, Byte> ANONYMOUS_SESSIONS = createField(DSL.name("anonymous_sessions"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>gamedata.organization_game.organization_id</code>.
     */
    public final TableField<OrganizationGameRecord, Integer> ORGANIZATION_ID = createField(DSL.name("organization_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>gamedata.organization_game.game_id</code>.
     */
    public final TableField<OrganizationGameRecord, Integer> GAME_ID = createField(DSL.name("game_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private OrganizationGame(Name alias, Table<OrganizationGameRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrganizationGame(Name alias, Table<OrganizationGameRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>gamedata.organization_game</code> table reference
     */
    public OrganizationGame(String alias) {
        this(DSL.name(alias), ORGANIZATION_GAME);
    }

    /**
     * Create an aliased <code>gamedata.organization_game</code> table reference
     */
    public OrganizationGame(Name alias) {
        this(alias, ORGANIZATION_GAME);
    }

    /**
     * Create a <code>gamedata.organization_game</code> table reference
     */
    public OrganizationGame() {
        this(DSL.name("organization_game"), null);
    }

    public <O extends Record> OrganizationGame(Table<O> child, ForeignKey<O, OrganizationGameRecord> key) {
        super(child, key, ORGANIZATION_GAME);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Gamedata.GAMEDATA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ORGANIZATION_GAME_FK_ORGANIZATION_GAME_GAME1_IDX, Indexes.ORGANIZATION_GAME_FK_ORGANIZATION_GAME_ORGANIZATION1_IDX);
    }

    @Override
    public Identity<OrganizationGameRecord, Integer> getIdentity() {
        return (Identity<OrganizationGameRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<OrganizationGameRecord> getPrimaryKey() {
        return Keys.KEY_ORGANIZATION_GAME_PRIMARY;
    }

    @Override
    public List<UniqueKey<OrganizationGameRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_ORGANIZATION_GAME_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<OrganizationGameRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_ORGANIZATION_GAME_ORGANIZATION1, Keys.FK_ORGANIZATION_GAME_GAME1);
    }

    private transient Organization _organization;
    private transient Game _game;

    /**
     * Get the implicit join path to the <code>gamedata.organization</code>
     * table.
     */
    public Organization organization() {
        if (_organization == null)
            _organization = new Organization(this, Keys.FK_ORGANIZATION_GAME_ORGANIZATION1);

        return _organization;
    }

    /**
     * Get the implicit join path to the <code>gamedata.game</code> table.
     */
    public Game game() {
        if (_game == null)
            _game = new Game(this, Keys.FK_ORGANIZATION_GAME_GAME1);

        return _game;
    }

    @Override
    public OrganizationGame as(String alias) {
        return new OrganizationGame(DSL.name(alias), this);
    }

    @Override
    public OrganizationGame as(Name alias) {
        return new OrganizationGame(alias, this);
    }

    @Override
    public OrganizationGame as(Table<?> alias) {
        return new OrganizationGame(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrganizationGame rename(String name) {
        return new OrganizationGame(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrganizationGame rename(Name name) {
        return new OrganizationGame(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrganizationGame rename(Table<?> name) {
        return new OrganizationGame(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, Byte, Byte, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super Integer, ? super String, ? super Byte, ? super Byte, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super Integer, ? super String, ? super Byte, ? super Byte, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
