/*
 * This file is generated by jOOQ.
 */
package nl.gamedata.data.tables;


import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import nl.gamedata.data.Gamedata;
import nl.gamedata.data.Indexes;
import nl.gamedata.data.Keys;
import nl.gamedata.data.tables.records.OrgGameRoleRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrgGameRole extends TableImpl<OrgGameRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>gamedata.org_game_role</code>
     */
    public static final OrgGameRole ORG_GAME_ROLE = new OrgGameRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrgGameRoleRecord> getRecordType() {
        return OrgGameRoleRecord.class;
    }

    /**
     * The column <code>gamedata.org_game_role.id</code>.
     */
    public final TableField<OrgGameRoleRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>gamedata.org_game_role.session_admin</code>.
     */
    public final TableField<OrgGameRoleRecord, Byte> SESSION_ADMIN = createField(DSL.name("session_admin"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>gamedata.org_game_role.session_viewer</code>.
     */
    public final TableField<OrgGameRoleRecord, Byte> SESSION_VIEWER = createField(DSL.name("session_viewer"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>gamedata.org_game_role.game_access_id</code>.
     */
    public final TableField<OrgGameRoleRecord, Integer> GAME_ACCESS_ID = createField(DSL.name("game_access_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>gamedata.org_game_role.organization_role_id</code>.
     */
    public final TableField<OrgGameRoleRecord, Integer> ORGANIZATION_ROLE_ID = createField(DSL.name("organization_role_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private OrgGameRole(Name alias, Table<OrgGameRoleRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrgGameRole(Name alias, Table<OrgGameRoleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>gamedata.org_game_role</code> table reference
     */
    public OrgGameRole(String alias) {
        this(DSL.name(alias), ORG_GAME_ROLE);
    }

    /**
     * Create an aliased <code>gamedata.org_game_role</code> table reference
     */
    public OrgGameRole(Name alias) {
        this(alias, ORG_GAME_ROLE);
    }

    /**
     * Create a <code>gamedata.org_game_role</code> table reference
     */
    public OrgGameRole() {
        this(DSL.name("org_game_role"), null);
    }

    public <O extends Record> OrgGameRole(Table<O> child, ForeignKey<O, OrgGameRoleRecord> key) {
        super(child, key, ORG_GAME_ROLE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Gamedata.GAMEDATA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ORG_GAME_ROLE_FK_ORG_GAME_ROLE_GAME_ACCESS1_IDX, Indexes.ORG_GAME_ROLE_FK_ORG_GAME_ROLE_ORGANIZATION_ROLE1_IDX);
    }

    @Override
    public Identity<OrgGameRoleRecord, Integer> getIdentity() {
        return (Identity<OrgGameRoleRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<OrgGameRoleRecord> getPrimaryKey() {
        return Keys.KEY_ORG_GAME_ROLE_PRIMARY;
    }

    @Override
    public List<UniqueKey<OrgGameRoleRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_ORG_GAME_ROLE_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<OrgGameRoleRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_ORG_GAME_ROLE_GAME_ACCESS1, Keys.FK_ORG_GAME_ROLE_ORGANIZATION_ROLE1);
    }

    private transient GameAccess _gameAccess;
    private transient OrganizationRole _organizationRole;

    /**
     * Get the implicit join path to the <code>gamedata.game_access</code>
     * table.
     */
    public GameAccess gameAccess() {
        if (_gameAccess == null)
            _gameAccess = new GameAccess(this, Keys.FK_ORG_GAME_ROLE_GAME_ACCESS1);

        return _gameAccess;
    }

    /**
     * Get the implicit join path to the <code>gamedata.organization_role</code>
     * table.
     */
    public OrganizationRole organizationRole() {
        if (_organizationRole == null)
            _organizationRole = new OrganizationRole(this, Keys.FK_ORG_GAME_ROLE_ORGANIZATION_ROLE1);

        return _organizationRole;
    }

    @Override
    public OrgGameRole as(String alias) {
        return new OrgGameRole(DSL.name(alias), this);
    }

    @Override
    public OrgGameRole as(Name alias) {
        return new OrgGameRole(alias, this);
    }

    @Override
    public OrgGameRole as(Table<?> alias) {
        return new OrgGameRole(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrgGameRole rename(String name) {
        return new OrgGameRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrgGameRole rename(Name name) {
        return new OrgGameRole(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrgGameRole rename(Table<?> name) {
        return new OrgGameRole(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Byte, Byte, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super Integer, ? super Byte, ? super Byte, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super Integer, ? super Byte, ? super Byte, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
