/*
 * This file is generated by jOOQ.
 */
package nl.gamedata.data.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import nl.gamedata.data.Gamedata;
import nl.gamedata.data.Indexes;
import nl.gamedata.data.Keys;
import nl.gamedata.data.tables.records.PlayerLogdataRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerLogdata extends TableImpl<PlayerLogdataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>gamedata.player_logdata</code>
     */
    public static final PlayerLogdata PLAYER_LOGDATA = new PlayerLogdata();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlayerLogdataRecord> getRecordType() {
        return PlayerLogdataRecord.class;
    }

    /**
     * The column <code>gamedata.player_logdata.id</code>.
     */
    public final TableField<PlayerLogdataRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>gamedata.player_logdata.type</code>.
     */
    public final TableField<PlayerLogdataRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>gamedata.player_logdata.key</code>.
     */
    public final TableField<PlayerLogdataRecord, String> KEY = createField(DSL.name("key"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>gamedata.player_logdata.value</code>.
     */
    public final TableField<PlayerLogdataRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>gamedata.player_logdata.timestamp</code>.
     */
    public final TableField<PlayerLogdataRecord, LocalDateTime> TIMESTAMP = createField(DSL.name("timestamp"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>gamedata.player_logdata.mission_attempt</code>.
     */
    public final TableField<PlayerLogdataRecord, Integer> MISSION_ATTEMPT = createField(DSL.name("mission_attempt"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>gamedata.player_logdata.player_id</code>.
     */
    public final TableField<PlayerLogdataRecord, Integer> PLAYER_ID = createField(DSL.name("player_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private PlayerLogdata(Name alias, Table<PlayerLogdataRecord> aliased) {
        this(alias, aliased, null);
    }

    private PlayerLogdata(Name alias, Table<PlayerLogdataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>gamedata.player_logdata</code> table reference
     */
    public PlayerLogdata(String alias) {
        this(DSL.name(alias), PLAYER_LOGDATA);
    }

    /**
     * Create an aliased <code>gamedata.player_logdata</code> table reference
     */
    public PlayerLogdata(Name alias) {
        this(alias, PLAYER_LOGDATA);
    }

    /**
     * Create a <code>gamedata.player_logdata</code> table reference
     */
    public PlayerLogdata() {
        this(DSL.name("player_logdata"), null);
    }

    public <O extends Record> PlayerLogdata(Table<O> child, ForeignKey<O, PlayerLogdataRecord> key) {
        super(child, key, PLAYER_LOGDATA);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Gamedata.GAMEDATA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PLAYER_LOGDATA_FK_PLAYERLOGDATA_PLAYER1_IDX);
    }

    @Override
    public Identity<PlayerLogdataRecord, Integer> getIdentity() {
        return (Identity<PlayerLogdataRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<PlayerLogdataRecord> getPrimaryKey() {
        return Keys.KEY_PLAYER_LOGDATA_PRIMARY;
    }

    @Override
    public List<UniqueKey<PlayerLogdataRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_PLAYER_LOGDATA_ID_UNIQUE);
    }

    @Override
    public List<ForeignKey<PlayerLogdataRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_PLAYERLOGDATA_PLAYER1);
    }

    private transient Player _player;

    /**
     * Get the implicit join path to the <code>gamedata.player</code> table.
     */
    public Player player() {
        if (_player == null)
            _player = new Player(this, Keys.FK_PLAYERLOGDATA_PLAYER1);

        return _player;
    }

    @Override
    public PlayerLogdata as(String alias) {
        return new PlayerLogdata(DSL.name(alias), this);
    }

    @Override
    public PlayerLogdata as(Name alias) {
        return new PlayerLogdata(alias, this);
    }

    @Override
    public PlayerLogdata as(Table<?> alias) {
        return new PlayerLogdata(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerLogdata rename(String name) {
        return new PlayerLogdata(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerLogdata rename(Name name) {
        return new PlayerLogdata(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerLogdata rename(Table<?> name) {
        return new PlayerLogdata(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, LocalDateTime, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super Integer, ? super String, ? super String, ? super String, ? super LocalDateTime, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super Integer, ? super String, ? super String, ? super String, ? super LocalDateTime, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
